### ISSUE TITLE
lo mado bega

### ISSUE THREAD

**Issue by 99003510** [99003510/Miniprojet_Kernal-drivers#1]
![Untitled Diagram](https://user-images.githubusercontent.com/78545203/112936278-1e2c7b00-9143-11eb-9841-f0b7fb6d8bef.png)

**Comment by 99003597** [comment]
![Screenshot from 2021-03-30 10-49-19](https://user-images.githubusercontent.com/78539729/112937763-e07d2180-9145-11eb-8e6b-a3879dd2d40d.png)

**Comment by 99003597** [comment]
i am adding in readme
